name: Update Reddit Comments

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at midnight (00:00 UTC) every Sunday
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  update_comments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Attempt to download the latest database artifact
      uses: actions/download-artifact@v3
      with:
        name: reddit-comments-db
        path: ${{ runner.temp }}/sqlite
      continue-on-error: true  # Continue even if the artifact is not found

    - name: Move database if it exists
      run: |
        if [ -f "${{ runner.temp }}/sqlite/reddit_comments.db" ]; then
          mv "${{ runner.temp }}/sqlite/reddit_comments.db" reddit_comments.db
        fi

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install praw python-dotenv tqdm

    - name: Run the Reddit comments fetch script
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
        TARGET_USERNAME: ${{ secrets.TARGET_USERNAME }}
        LIMIT: ${{ secrets.LIMIT }}
        TILL_LAST_COMMENT: true  # Adjust based on whether you want to fetch since the last comment
      run: |
        python fetch_comments.py
    
    - name: Set up Pandoc
      run: |
        sudo apt-get install -y pandoc texlive texlive-xetex texlive-fonts-recommended

    - name: Run the markdown generation script
      run: |
        python generate_markdown.py
    
    - name: Commit and push changes if markdown files were created
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ven_anigha_reddit_archive_*.md reddit_comments.db
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update Reddit comments and markdown files"
          git push origin HEAD:${{ github.ref }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Store database persistently
      uses: actions/upload-artifact@v3
      with:
        name: reddit-comments-db
        path: reddit_comments.db